### ISSUE TITLE
Integrating Mixpanel as a Framework breaks Tweaks

### ISSUE THREAD

**Issue by arittr** [mixpanel/mixpanel-iphone#346]
Integrating Mixpanel with CocoaPods v0.36+ and use_frameworks prevents Tweaks from appearing in the UI (or being found / stored in general). 

It appears the the issue has something to do with the macro not being included in the output framework - the relevant line is https://github.com/mixpanel/mixpanel-iphone/blob/master/Mixpanel/MPTweakInline.m#L127 , which will return null when using frameworks. It looks like the whole function is just undefined in the final SDK binary:

"@MPTweak *_MPTweakCreateWithEntry(NSString *__strong, mp_tweak_entry *)^@<Unknown Function>

**Comment by RTimal** [comment]
I'm experiencing this as well

**Comment by samgreen** [comment]
#364 should fix that

**Comment by phin** [comment]
+1, experiencing this issue as well

**Comment by samgreen** [comment]
This is now released as v2.9.2, thanks for your patience!

**Comment by z4r** [comment]
I still have the same issue with the v2.9.3 and v2.9.4 installed via Carthage.
The visibility is provided only for the main header `Mixpanel.h` and any symbol related to `MPTweakInline.h` is not available.

![Mixpanel Header](https://cloud.githubusercontent.com/assets/639459/13325925/336e97f6-dbe4-11e5-9bd1-7426f7b8cad5.png)
